### PR TITLE
sane-backends: updates to saned non-root proposal (WIP)

### PR DESCRIPTION
**Pull request by danielfdickinson**
Hi Luiz,

I've made some updates based on / for my testing.  Hope it helps.  See also https://github.com/openwrt/packages/pull/8851and https://github.com/openwrt/packages/pull/9583 (the latter is my non-root p910nd PR).

Modified from https://github.com/luizluca/openwrt-packages/tree/sane-hotplug/utils/sane-backends

with the code to set group to saned for usblp device removed (that belongs to
p910nd and isn't needed for saned).

Also, we make non-root default for xinetd and set permissions on the
config files.

TODO: Handle non-HP printer/scanners/all-in-one devices
TODO: Optionalize use of saned as user (i.e. allow user to
      pick user as which to run, including root)
TODO: Remove unnecessary write access on config files
TODO: Remove unnecessary read access on usblp/*/bind

Signed-off-by: Daniel F. Dickinson <cshored@thecshore.com>

Maintainer: me / @\<github-user> (find it by checking history of the package Makefile)
Compile tested: (put here arch, model, OpenWrt version)
Run tested: (put here arch, model, OpenWrt version, tests done)

Description:

### CODE REVIEW

**Comment by danielfdickinson** [comment]
Updated with a fix for the "bind" vs "add" issue:

@luizluca I've noticed that on reboot (but not on initial plugin of the device) that the hp all-in-one I have only does a "bind" not "add" for the "usb_interface" hotplug event.
e.g. here are all the events that occur for me during boot:
```
add usb_device /devices/platform/ahb/1b000000.usb/usb1
add usb_device /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.3
add usb_device /devices/platform/ahb/1b000000.usb/usb1/1-1
add usb_device /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.2
bind usb_interface /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.3/1-1.3:1.1
bind usb_interface /devices/platform/ahb/1b000000.usb/usb1/1-1/1-1.2/1-1.2:1.0
```
Since 20-saned is checking for an "add" on "usb_interface" during boot the /dev/bus/usb/xxx/xxx device doesn't get the saned group chown.
I'm working on a patch.

**Comment by danielfdickinson** [comment]
@luizluca Any thoughts on what you'd like to see done with this (the p910nd PR was accepted)?  I ought to have enough time to make the necessary changes for the next couple of weeks, at least.

**Comment by luizluca** [comment]
Hello @cshoredaniel ,

I'm dealing with an issue with ruby and musl dlsym() on MIPS. ASAP, I'll get back to this.

**Comment by danielfdickinson** [comment]
Ok, thanks for letting me know.

**Comment by luizluca** [comment]
@cshoredaniel , I did my overdue update on this problem.
Please, check my updated sane-hotplug (586f491e82027c0dea7193b0dd926ed9d222345b) branch.
It was rebased on master recently. Also it updates sane-backends to 1.0.28, however I did not test it yet (only the hotplug scripts).

Hotplug is much simpler now. When a scanner is added, it simply grant g+w /sys/bus/usb/drivers/usblp/bind and g+rw to "/dev/$DEVNAME". The catch is how to tell whether
an USB device is a scanner or not. I collect vendor/product id from sane-backends and hplip and
build a product database with multiple files like /usr/share/sane/03f0-hplip.usbid.

It still lacks permission for conf files. I would not like to grant with the hotplug script because
it might touch multiple times the flash. However, I didn't spend too much time thinking about it yet.

I also needs some postinst script to deal with printers already connected at the time saned was installed. I still did not test the behavior during a boot.

**Comment by luizluca** [comment]
I'll close this as we have https://github.com/openwrt/packages/pull/10425 now

**Comment by danielfdickinson** [comment]
Will look at the new PR soon-ish.  Thank you for your work!

**Comment by danielfdickinson** [comment]
Will test soon.  For conf files they should probably only have 
permission changes on package install, so uci-defaults would be fine I 
think (and not be a flash wearout issue).

It's not like files in /etc should change unless the user deliberately 
does something anyway.

**Pull request closed without merging**
